### Register User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johnDoe1@example.com",
  "password": "123"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "12345" 
}

### Get User
GET http://localhost:3000/users/2

### Update User
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "id": "1",  
  "name": "John Smith",
  "email": "john.smith@example.com"
}

### Delete User
DELETE http://localhost:3000/users/1
